"""LGPD cascade deletes

Revision ID: 0e50bf2990ea
Revises: 532c7939e819
Create Date: 2026-09-04 21:15:37.623405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e50bf2990ea'
down_revision = '532c7939e819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chat_message_sender_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('contact_messages_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_log_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('forum_post_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('forum_topic', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('forum_topic_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('system_feedback', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('system_feedback_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('system_feedback_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('forum_topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('forum_topic_author_id_fkey'), 'user', ['author_id'], ['id'])

    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('forum_post_author_id_fkey'), 'user', ['author_id'], ['id'])

    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_log_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('contact_messages_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chat_message_sender_id_fkey'), 'user', ['sender_id'], ['id'])

    # ### end Alembic commands ###
