"""Add onboarding_status to User

Revision ID: 133035cf8654
Revises: 29e1fba1c42e
Create Date: 2025-12-16 20:28:25.691696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '133035cf8654'
down_revision = '29e1fba1c42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_status', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('onboarding_status')

    # ### end Alembic commands ###
