"""Contagem Atribuidas Atividades

Revision ID: 18e161db005d
Revises: d767de2f2a5b
Create Date: 2025-08-19 18:22:24.644195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e161db005d'
down_revision = 'd767de2f2a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_count', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('assignment_count')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('assignment_count')

    # ### end Alembic commands ###
