"""Adiciona copy_count com server_default

Revision ID: 191693916c4d
Revises: 1f726c812dcb
Create Date: 2025-07-28 19:03:33.981026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191693916c4d'
down_revision = '1f726c812dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('copy_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('copy_count')

    # ### end Alembic commands ###
