"""Add coins_earned to ActivityProgress

Revision ID: 1d2e0fa738a9
Revises: 392fedde09ec
Create Date: 2025-10-28 16:01:05.792108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2e0fa738a9'
down_revision = '392fedde09ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins_earned', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.drop_column('coins_earned')

    # ### end Alembic commands ###
