"""Criação inicial de todas as tabelas

Revision ID: 1f726c812dcb
Revises: 
Create Date: 2025-07-25 16:34:27.932123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f726c812dcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('given_by_id', sa.Integer(), nullable=False),
    sa.Column('score_adjustment', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['given_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['student_response.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('student_achievement')
    op.drop_table('activity_element')
    op.drop_table('feedback')
    op.drop_table('gamification_element')
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('activity_progress_student_id_activity_id_key'), type_='unique')
        batch_op.create_unique_constraint('_student_activity_uc', ['student_id', 'activity_id'])

    with op.batch_alter_table('activity_revision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
        batch_op.add_column(sa.Column('revision_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('revised_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('activity_revision_activity_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('activity_revision_revised_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'activity', ['activity_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['revised_by_id'], ['id'])
        batch_op.drop_column('change_note')
        batch_op.drop_column('revision')
        batch_op.drop_column('revised_by')
        batch_op.drop_column('data_snapshot')

    with op.batch_alter_table('activity_tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('activity_tag_tag_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('activity_tag_activity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'activity', ['activity_id'], ['id'])
        batch_op.create_foreign_key(None, 'tag', ['tag_id'], ['id'])

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('xp')
        batch_op.drop_column('points')
        batch_op.drop_column('level')

    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_event_log_user'))
        batch_op.drop_constraint(batch_op.f('event_log_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('metadata')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')

    with op.batch_alter_table('student_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_responses_progress'))
        batch_op.drop_constraint(batch_op.f('student_response_progress_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'activity', ['activity_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['student_id'], ['id'])
        batch_op.drop_column('step_identifier')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('progress_id')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_tags_category'))
        batch_op.drop_constraint(batch_op.f('tag_created_by_fkey'), type_='foreignkey')
        batch_op.drop_column('category')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('tag_created_by_fkey'), 'user', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_tags_category'), ['category'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('description')

    with op.batch_alter_table('student_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('submitted_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('step_identifier', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_response_progress_id_fkey'), 'activity_progress', ['progress_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_responses_progress'), ['progress_id', 'step_identifier'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('activity_id')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_log_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_event_log_user'), ['user_id', 'created_at'], unique=False)
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=50),
               type_=postgresql.INET(),
               existing_nullable=True)
        batch_op.alter_column('event_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('event_data')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('xp', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('activity_tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('activity_tag_activity_id_fkey'), 'activity', ['activity_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('activity_tag_tag_id_fkey'), 'tag', ['tag_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('activity_revision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('revised_by', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('revision', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('change_note', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('activity_revision_revised_by_fkey'), 'user', ['revised_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('activity_revision_activity_id_fkey'), 'activity', ['activity_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('revised_by_id')
        batch_op.drop_column('revision_notes')
        batch_op.drop_column('revision_data')

    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.drop_constraint('_student_activity_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('activity_progress_student_id_activity_id_key'), ['student_id', 'activity_id'], postgresql_nulls_not_distinct=False)

    op.create_table('gamification_element',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('gamification_element_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('points_value', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gamification_element_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('progress_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('professor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback_type', sa.VARCHAR(length=20), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('points_adjust', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['user.id'], name=op.f('feedback_professor_id_fkey')),
    sa.ForeignKeyConstraint(['progress_id'], ['activity_progress.id'], name=op.f('feedback_progress_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey'))
    )
    op.create_table('activity_element',
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('element_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('activity_element_activity_id_fkey')),
    sa.ForeignKeyConstraint(['element_id'], ['gamification_element.id'], name=op.f('activity_element_element_id_fkey')),
    sa.PrimaryKeyConstraint('activity_id', 'element_id', name=op.f('activity_element_pkey'))
    )
    op.create_table('student_achievement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('element_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('earned_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('student_achievement_activity_id_fkey')),
    sa.ForeignKeyConstraint(['element_id'], ['gamification_element.id'], name=op.f('student_achievement_element_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('student_achievement_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_achievement_pkey')),
    sa.UniqueConstraint('student_id', 'element_id', 'activity_id', name=op.f('student_achievement_student_id_element_id_activity_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('manual_feedback')
    # ### end Alembic commands ###
