"""Adiciona global_xp ao User

Revision ID: 2f8ba9551a24
Revises: 7229cd996e6a
Create Date: 2025-11-14 14:16:40.929899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8ba9551a24'
down_revision = '7229cd996e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('global_xp', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('global_xp')

    # ### end Alembic commands ###
