"""Add last known location to User model

Revision ID: 392fedde09ec
Revises: 78f8463c4537
Create Date: 2025-10-15 17:06:37.073116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392fedde09ec'
down_revision = '78f8463c4537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_known_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_known_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_location_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_location_update')
        batch_op.drop_column('last_known_longitude')
        batch_op.drop_column('last_known_latitude')

    # ### end Alembic commands ###
