"""tabela de eventlog alterada

Revision ID: 39b6ac2ece80
Revises: d52e0596e3e4
Create Date: 2025-08-29 14:49:47.643902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b6ac2ece80'
down_revision = 'd52e0596e3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('section',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'unknown'::character varying"))
        batch_op.create_foreign_key(None, 'activity', ['activity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('section',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('activity_id')

    # ### end Alembic commands ###
