"""add time to complete the activity

Revision ID: 3a0362a795e4
Revises: 1d2e0fa738a9
Create Date: 2025-10-30 14:35:59.759798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0362a795e4'
down_revision = '1d2e0fa738a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_from', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('available_from')

    # ### end Alembic commands ###
