"""Add SystemStat table

Revision ID: 532c7939e819
Revises: a2c7b7861bf7
Create Date: 2026-08-30 12:24:00.418892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532c7939e819'
down_revision = 'a2c7b7861bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_stat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_stat_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_stat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_stat_key'))

    op.drop_table('system_stat')
    # ### end Alembic commands ###
