"""add cached location

Revision ID: 680634fd190e
Revises: 3a0362a795e4
Create Date: 2025-11-13 15:34:57.383830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680634fd190e'
down_revision = '3a0362a795e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cached_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cached_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cached_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cached_suburb', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cached_suburb')
        batch_op.drop_column('cached_country')
        batch_op.drop_column('cached_state')
        batch_op.drop_column('cached_city')

    # ### end Alembic commands ###
