"""class details page edit

Revision ID: 78f8463c4537
Revises: 1222c5f0315b
Create Date: 2025-10-14 14:27:43.710785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f8463c4537'
down_revision = '1222c5f0315b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_enrollment_code_public', sa.Boolean(), nullable=False, server_default='f'))


    with op.batch_alter_table('forum_topic', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'forum_post', ['best_answer_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('is_enrollment_code_public')

    # ### end Alembic commands ###
