"""add is_pinned to forum topic

Revision ID: 7c0e0d6fe5f0
Revises: bf9dabec6511
Create Date: 2025-10-08 18:08:05.306311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0e0d6fe5f0'
down_revision = 'bf9dabec6511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_topic', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'forum_post', ['best_answer_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
