"""add learningcontent

Revision ID: 7cc22f57e49a
Revises: 2f8ba9551a24
Create Date: 2025-12-02 16:21:59.373753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc22f57e49a'
down_revision = '2f8ba9551a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=50), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('material_link', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'step_id', name='_activity_step_uc_learning')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_content')
    # ### end Alembic commands ###
