"""Adiciona campos de gamificacao a tabela Enrollment

Revision ID: 83b92c45c903
Revises: fdf75e88c764
Create Date: 2025-07-24 18:29:20.757241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b92c45c903'
down_revision = 'fdf75e88c764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('xp')
        batch_op.drop_column('level')
        batch_op.drop_column('points')

    # ### end Alembic commands ###
