"""Add Activity model

Revision ID: 8d47205c3e0d
Revises: 
Create Date: 2025-07-06 18:13:10.207255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d47205c3e0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_scenario', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('desired_scenario', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activity_planning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('player_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('game_elements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rewards_offered', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rewarded_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gamification_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('area_knowledge', sa.String(length=100), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
