"""add api keys to user

Revision ID: a2c7b7861bf7
Revises: d6b206e8486c
Create Date: 2026-08-29 23:22:13.161015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c7b7861bf7'
down_revision = 'd6b206e8486c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gemini_api_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('openai_api_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('openai_api_key')
        batch_op.drop_column('gemini_api_key')

    # ### end Alembic commands ###
