"""Add Class and Enrollment models, and link Activity to Class

Revision ID: a6653c69ef02
Revises: <NOVO_ID_DE_REVISAO>
Create Date: 2025-07-16 17:24:49.976092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6653c69ef02'
down_revision = '<NOVO_ID_DE_REVISAO>'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_id', name='_student_class_uc')
    )
    op.drop_table('student_class_association')
    op.drop_table('activity_class_association')
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('enrollment_code', sa.String(length=50), nullable=False))
        batch_op.drop_constraint(batch_op.f('class_join_code_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['enrollment_code'])
        batch_op.drop_constraint(batch_op.f('class_teacher_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['professor_id'], ['id'])
        batch_op.drop_column('join_code')
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_info')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('profile_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('join_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('class_teacher_id_fkey'), 'user', ['teacher_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('class_join_code_key'), ['join_code'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('enrollment_code')
        batch_op.drop_column('professor_id')

    op.create_table('activity_class_association',
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('activity_class_association_activity_id_fkey')),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name=op.f('activity_class_association_class_id_fkey')),
    sa.PrimaryKeyConstraint('activity_id', 'class_id', name=op.f('activity_class_association_pkey'))
    )
    op.create_table('student_class_association',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name=op.f('student_class_association_class_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('student_class_association_student_id_fkey')),
    sa.PrimaryKeyConstraint('student_id', 'class_id', name=op.f('student_class_association_pkey'))
    )
    op.drop_table('enrollment')
    # ### end Alembic commands ###
