"""atualizando dados para tabuleiro2

Revision ID: b9a392380170
Revises: da42913f41ab
Create Date: 2025-09-12 15:31:52.233258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9a392380170'
down_revision = 'da42913f41ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gamification_design', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('game_board_layout')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_board_layout', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('gamification_design')

    # ### end Alembic commands ###
