"""add contact and refac models

Revision ID: bc77fa8db42f
Revises: 7cc22f57e49a
Create Date: 2025-12-09 17:51:57.198086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc77fa8db42f'
down_revision = '7cc22f57e49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.drop_column('coins_earned')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins_earned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    op.drop_table('contact_messages')
    # ### end Alembic commands ###
