"""Change StoreItem effect_id to JSONB

Revision ID: be89e69ec032
Revises: ce460c77c4bc
Create Date: 2025-10-02 12:53:47.637538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be89e69ec032'
down_revision = 'ce460c77c4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_item', schema=None) as batch_op:
        batch_op.alter_column('effect_id',
               existing_type=sa.VARCHAR(length=100),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               # ADICIONE ESTA LINHA:
               postgresql_using='effect_id::jsonb')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_item', schema=None) as batch_op:
        batch_op.alter_column('effect_id',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               # ADICIONE ESTA LINHA (PARA GARANTIR A REVERSÃO):
               postgresql_using='effect_id::text')

    # ### end Alembic commands ###
