"""Add is_draft column to Activity

Revision ID: caf7c28f1bde
Revises: 133035cf8654
Create Date: 2026-01-06 16:49:04.740920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf7c28f1bde'
down_revision = '133035cf8654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), server_default='f', nullable=False))
        batch_op.create_index(batch_op.f('ix_activity_is_draft'), ['is_draft'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_is_draft'))
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###
