"""Add title system

Revision ID: ce460c77c4bc
Revises: fe5d85658420
Create Date: 2025-10-01 17:09:39.636043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce460c77c4bc'
down_revision = 'fe5d85658420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effect_id', sa.String(length=100), nullable=False),
    sa.Column('display_text', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effect_id')
    )
    op.create_table('user_unlocked_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['title.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_id', 'title_id', name='_user_activity_title_uc')
    )
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipped_title_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'title', ['equipped_title_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipped_title_id')

    op.drop_table('user_unlocked_title')
    op.drop_table('title')
    # ### end Alembic commands ###
