"""Add total_xp_earned to ActivityProgress

Revision ID: d42b65686240
Revises: 9312bf376623
Create Date: 2025-08-26 19:41:00.212259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42b65686240'
down_revision = '9312bf376623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_xp_earned', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.drop_column('total_xp_earned')

    # ### end Alembic commands ###
