"""Refactor EventLog model for structured analytics2

Revision ID: d52e0596e3e4
Revises: dfab23e7cd58
Create Date: 2025-08-29 13:37:24.739349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd52e0596e3e4'
down_revision = 'dfab23e7cd58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.String(length=100), nullable=False, server_default='unknown'))
        batch_op.add_column(sa.Column('action', sa.String(length=100), nullable=False, server_default='unknown'))
        batch_op.add_column(sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('event_type')
        batch_op.drop_column('event_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('details')
        batch_op.drop_column('action')
        batch_op.drop_column('section')

    # ### end Alembic commands ###
