"""add_indexes

Revision ID: d6b206e8486c
Revises: f525a5e0e680
Create Date: 2026-08-29 21:14:36.318801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b206e8486c'
down_revision = 'f525a5e0e680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_professor_id'), ['professor_id'], unique=False)

    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_progress_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_progress_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_progress_equipped_name_cosmetic_id'), ['equipped_name_cosmetic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_progress_equipped_title_cosmetic_id'), ['equipped_title_cosmetic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_progress_equipped_title_id'), ['equipped_title_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_progress_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('activity_rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_rating_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_rating_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('activity_revision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_revision_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_revision_revised_by_id'), ['revised_by_id'], unique=False)

    with op.batch_alter_table('activity_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_tag_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_tag_tag_id'), ['tag_id'], unique=False)

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_sender_id'), ['sender_id'], unique=False)

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_professor_id'), ['professor_id'], unique=False)

    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conversation_activity_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_conversation_activity_id'), ['activity_id'], unique=True)

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_participants_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_participants_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollment_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_log_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('forum_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_category_activity_id'), ['activity_id'], unique=False)

    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_post_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_post_topic_id'), ['topic_id'], unique=False)

    with op.batch_alter_table('forum_topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_topic_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_topic_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_topic_best_answer_id'), ['best_answer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_topic_category_id'), ['category_id'], unique=False)

    with op.batch_alter_table('learning_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_content_activity_id'), ['activity_id'], unique=False)

    with op.batch_alter_table('manual_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_feedback_given_by_id'), ['given_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_feedback_response_id'), ['response_id'], unique=False)

    with op.batch_alter_table('message_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_report_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_report_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('narrative_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_narrative_content_activity_id'), ['activity_id'], unique=False)

    with op.batch_alter_table('post_like', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_like_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_like_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('quiz_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_content_activity_id'), ['activity_id'], unique=False)

    with op.batch_alter_table('roulette_win', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roulette_win_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roulette_win_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('slot_win', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slot_win_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_slot_win_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('store_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_item_activity_id'), ['activity_id'], unique=False)

    with op.batch_alter_table('student_response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_response_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_response_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('system_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_feedback_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_class_id'), ['class_id'], unique=False)

    with op.batch_alter_table('topic_like', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_like_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_like_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_unlocked_medal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_unlocked_medal_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_unlocked_medal_medal_id'), ['medal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_unlocked_medal_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_unlocked_title', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_unlocked_title_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_unlocked_title_title_id'), ['title_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_unlocked_title_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_unlocked_title', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_unlocked_title_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_unlocked_title_title_id'))
        batch_op.drop_index(batch_op.f('ix_user_unlocked_title_activity_id'))

    with op.batch_alter_table('user_unlocked_medal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_unlocked_medal_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_unlocked_medal_medal_id'))
        batch_op.drop_index(batch_op.f('ix_user_unlocked_medal_activity_id'))

    with op.batch_alter_table('topic_like', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_like_user_id'))
        batch_op.drop_index(batch_op.f('ix_topic_like_topic_id'))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_class_id'))

    with op.batch_alter_table('system_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_feedback_user_id'))

    with op.batch_alter_table('student_response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_response_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_response_activity_id'))

    with op.batch_alter_table('store_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_item_activity_id'))

    with op.batch_alter_table('slot_win', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slot_win_user_id'))
        batch_op.drop_index(batch_op.f('ix_slot_win_activity_id'))

    with op.batch_alter_table('roulette_win', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roulette_win_user_id'))
        batch_op.drop_index(batch_op.f('ix_roulette_win_activity_id'))

    with op.batch_alter_table('quiz_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_content_activity_id'))

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_user_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_item_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_activity_id'))

    with op.batch_alter_table('post_like', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_like_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_like_post_id'))

    with op.batch_alter_table('narrative_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_narrative_content_activity_id'))

    with op.batch_alter_table('message_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_report_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_report_message_id'))

    with op.batch_alter_table('manual_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_feedback_response_id'))
        batch_op.drop_index(batch_op.f('ix_manual_feedback_given_by_id'))

    with op.batch_alter_table('learning_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_content_activity_id'))

    with op.batch_alter_table('forum_topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_topic_category_id'))
        batch_op.drop_index(batch_op.f('ix_forum_topic_best_answer_id'))
        batch_op.drop_index(batch_op.f('ix_forum_topic_author_id'))
        batch_op.drop_index(batch_op.f('ix_forum_topic_activity_id'))

    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_post_topic_id'))
        batch_op.drop_index(batch_op.f('ix_forum_post_author_id'))

    with op.batch_alter_table('forum_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_category_activity_id'))

    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_log_activity_id'))

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollment_team_id'))
        batch_op.drop_index(batch_op.f('ix_enrollment_student_id'))
        batch_op.drop_index(batch_op.f('ix_enrollment_class_id'))

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_participants_conversation_id'))

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_activity_id'))
        batch_op.create_unique_constraint(batch_op.f('conversation_activity_id_key'), ['activity_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_user_id'))

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_professor_id'))

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_conversation_id'))

    with op.batch_alter_table('activity_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_tag_tag_id'))
        batch_op.drop_index(batch_op.f('ix_activity_tag_activity_id'))

    with op.batch_alter_table('activity_revision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_revision_revised_by_id'))
        batch_op.drop_index(batch_op.f('ix_activity_revision_activity_id'))

    with op.batch_alter_table('activity_rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_rating_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_rating_activity_id'))

    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_progress_student_id'))
        batch_op.drop_index(batch_op.f('ix_activity_progress_equipped_title_id'))
        batch_op.drop_index(batch_op.f('ix_activity_progress_equipped_title_cosmetic_id'))
        batch_op.drop_index(batch_op.f('ix_activity_progress_equipped_name_cosmetic_id'))
        batch_op.drop_index(batch_op.f('ix_activity_progress_class_id'))
        batch_op.drop_index(batch_op.f('ix_activity_progress_activity_id'))

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_professor_id'))
        batch_op.drop_index(batch_op.f('ix_activity_class_id'))

    # ### end Alembic commands ###
