"""Add narrative image url to Activity

Revision ID: d767de2f2a5b
Revises: 191693916c4d
Create Date: 2025-07-30 15:23:53.986015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd767de2f2a5b'
down_revision = '191693916c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('narrative_image_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('narrative_image_url')

    # ### end Alembic commands ###
