"""atualizando dados para tabuleiro

Revision ID: da42913f41ab
Revises: 39b6ac2ece80
Create Date: 2025-09-12 13:59:58.235062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da42913f41ab'
down_revision = '39b6ac2ece80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_board_layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_steps', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))

    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_event_log_action_created'))
        batch_op.drop_index(batch_op.f('idx_event_log_activity_id'))
        batch_op.drop_index(batch_op.f('idx_event_log_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_event_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_event_log_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_event_log_action_created'), ['action', 'created_at'], unique=False)

    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.drop_column('completed_steps')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('game_board_layout')

    # ### end Alembic commands ###
