"""add avatar 

Revision ID: dda0928a6a1d
Revises: be89e69ec032
Create Date: 2025-10-06 15:07:54.441552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dda0928a6a1d'
down_revision = 'be89e69ec032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipped_activity_avatar_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('unlocked_activity_avatars', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlocked_global_avatars', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('unlocked_global_avatars')

    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.drop_column('unlocked_activity_avatars')
        batch_op.drop_column('equipped_activity_avatar_url')

    # ### end Alembic commands ###
