"""add equipped cosmetics to activity progress2

Revision ID: f333922191fc
Revises: dda0928a6a1d
Create Date: 2025-10-07 11:30:37.696550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f333922191fc'
down_revision = 'dda0928a6a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipped_name_cosmetic_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('equipped_title_cosmetic_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'store_item', ['equipped_title_cosmetic_id'], ['id'])
        batch_op.create_foreign_key(None, 'store_item', ['equipped_name_cosmetic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipped_title_cosmetic_id')
        batch_op.drop_column('equipped_name_cosmetic_id')

    # ### end Alembic commands ###
