"""Adiciona last_spin_date ao progresso da atividade

Revision ID: fbec7b3f4c7e
Revises: 18e161db005d
Create Date: 2025-08-22 14:11:18.311419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbec7b3f4c7e'
down_revision = '18e161db005d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_spin_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.drop_column('last_spin_date')

    # ### end Alembic commands ###
