"""Add content tables for quiz and narrative

Revision ID: fe5d85658420
Revises: b9a392380170
Create Date: 2025-09-12 16:49:37.170541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe5d85658420'
down_revision = 'b9a392380170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narrative_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=50), nullable=False),
    sa.Column('scenario', sa.String(length=255), nullable=True),
    sa.Column('characters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dialogue', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'step_id', name='_activity_step_uc_narrative')
    )
    op.create_table('quiz_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=50), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'step_id', name='_activity_step_uc_quiz')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_content')
    op.drop_table('narrative_content')
    # ### end Alembic commands ###
